### ISSUE TITLE
How to install plugins?

### ISSUE THREAD

**Issue by hjoukl** [boiteasite/cmsuno#2]
Hi,
this is a really really neat piece of software!

I can't seem to get to work any plugins, though.
The docs are not very explicit about this (I also read the French documentation, alas my French is not very good). I take it that one should for e.g. the "Scrollnav" plugin
- download scrollnav-master.zip
- extract in the uno/plugins folder
- rename the extracted folder scrollnav-master to scrollnav
- chown -R <webserver-running-user>:<webserver-running-user> scrollnav

Is that correct?
I don't see any plugins in the plugins section of the uno.php admin panel i.e. I can't "activate" a plugin there. I tried clearing the browser cache and restarting the webserver, to no avail.

Do I need to register the plugin somehow? What am I missing?

(I'm running on Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.20, Firefox 49.0.2)

What am I missing?

**Comment by boiteasite** [comment]
Hi Hjoukl,

Thanks for the compliments.

By default, you only see activated plugins. To display all plugins, you just have to click the **green arrow** on the left part of the buttons bar.

Regards

**Comment by hjoukl** [comment]
Duh. How could I miss that... ;-)

Thanks a lot for your help!
Best regards,
Holger
