### ISSUE TITLE
uno_menu.js error

### ISSUE THREAD

**Issue by tamascz** [boiteasite/cmsuno#9]
Chrome:
> Uncaught TypeError: Cannot read property 'className' of null
    at sMenu (uno_menu.js:45)
    at HTMLAnchorElement.<anonymous> (uno_menu.js:14)

Because of this(?) back and forth navigation without Scrollnav causes endless jumping , and first navigation element remains colored not the active.

**Comment by Torsten-K** [comment]
I experienced this error, too, the jumping up and down.

**Comment by boiteasite** [comment]
Hi,
This is fixed with the new V1.5.7. Sorry for delay. Thanks for your report.
Regards
